# Generated by Django 3.2.6 on 2021-08-16 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date of start game')),
                ('end_date_time', models.DateTimeField(null=True, verbose_name='Date of end game')),
                ('field_size', models.IntegerField(default=3, verbose_name='Playing field size')),
                ('state', models.IntegerField(choices=[(1, 'Progress game'), (2, 'Game over')], default=1, verbose_name='Game stats')),
                ('winner', models.IntegerField(choices=[(1, 'Player'), (2, 'Computer'), (3, 'Tie')], null=True, verbose_name='Winner game')),
                ('symbol_player', models.IntegerField(choices=[(1, 'X'), (-1, 'O')], verbose_name='Player symbol')),
                ('symbol_computer', models.IntegerField(choices=[(1, 'X'), (-1, 'O')], verbose_name='Computer symbol')),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Hard')], verbose_name='Game level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ('start_date_time',),
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='When the move is made')),
                ('column', models.IntegerField(verbose_name='Number column')),
                ('row', models.IntegerField(verbose_name='Number row')),
                ('value', models.IntegerField(choices=[(1, 'X'), (-1, 'O')], verbose_name='Cell value')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_moves', to='tictactoe.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Game move',
                'verbose_name_plural': 'Game moves',
                'ordering': ('date_time',),
            },
        ),
    ]
