# Generated by Django 3.2.5 on 2021-08-03 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время начала игры')),
                ('end_date_time', models.DateTimeField(null=True, verbose_name='Время завершения игры')),
                ('field_size', models.IntegerField(default=3, verbose_name='Размер игрового поля')),
                ('result_game', models.IntegerField(choices=[(1, 'Выиграл'), (2, 'Проиграл'), (3, 'Ничья')], null=True, verbose_name='Результат игры')),
                ('symbol_gamer', models.IntegerField(choices=[(1, 'O'), (2, 'X')], verbose_name='Символ, которым играет игрок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_move_owner', models.IntegerField(choices=[(1, 'Игрок'), (2, 'Компьютер')], verbose_name='Кто сделал ход')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Когда сделан ход')),
                ('number_column', models.IntegerField(verbose_name='Номер столбца')),
                ('number_row', models.IntegerField(verbose_name='Номер строки')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoe.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Ход',
                'verbose_name_plural': 'Ходы',
            },
        ),
    ]
